# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:


- script: |
    sudo apt-get install texlive-latex-extra
    echo Starting pdflatex
    pdflatex -interaction=nonstopmode main.tex
    echo $(ls) 
    echo done pdflatex
  displayName: 'Run a multi-line script'
