# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: Build
# - checkout: self
#   persistCredentials: true
#   clean: true
  jobs:
    - job: Build

      # variables:
      #   - group: GitHub_Settings  
      #   - name: GITHUB_REPO_NAME
      #     value: 'DevOps'  
      #   - name: GITHUB_REPO_URL
      #     value: 'https://github.com/alex-bax/DevOps/$(GITHUB_REPO_NAME)' 
      #   - name: GITHUB_USERNAME
      #     value: 'alex-bax'
      #   - name: GITHUB_PUSH_URL
      #     value: '$(GITHUB_)/$(GITHUB_REPO_NAME)'
      pool:
        vmImage: ubuntu-latest
 
      steps:
      - script: |
          sudo apt-get install texlive-latex-extra
          echo Starting pdflatex
          pdflatex -interaction=nonstopmode main.tex
          echo $(ls) 
          echo done pdflatex

          git config --global user.email "alex.tennis@live.dk"
          git config --global user.name "alex-bax"
          #git init
          
          git remote add origin https://$(gitPAT)@github.com/alex-bax/DevOps.git
          git checkout master

          git add .
          git commit -m "auto generated pdf from pipeline"
          #git pull origin master
          git status
          
          #MY_PAT=qm7zdmgl27yrr6dyyjpqtncannkthsa5mvll776zarndjirq5zna
          B64_PAT=$(printf "%s"":$MY_PAT" | base64)
          #git -c http.extraHeader="Authorization: Basic ${B64_PAT}" clone https://dev.azure.com/GroupNeutrals/MiniTwit/_git/LatexDevOps
          #git -c http.extraHeader="Authorization: Basic ${B64_PAT}" push
          git push origin master 

          # format for pushing to GIT: 
          #https://[Github Username]:[Github PAT]@github.com/[GitHub Repo Owner]/[Github Repo Name]
          #git push https://alex-bax:qm7zdmgl27yrr6dyyjpqtncannkthsa5mvll776zarndjirq5zna@github.com/alex-bax/DevOps
        

        displayName: 'Run a multi-line script'
